### ISSUE TITLE
Problem with SendInBlue connection ?

### ISSUE THREAD

**Issue by corentinchap** [nopSolutions/sendinblue-plugin-for-nopcommerce#11]
Hello,

I've noticed that I had some issue with the SMTP relay on my NopCommerce instance lately.
The IP stated in my log is the following : 
0.152.29.81

This is not a valid address, hence the connection problem with SendInBlue.
Any idea on why this is happening ?

is there any problems on SendInBlue side ?

Error log is :
Nop.Core.NopException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Nop.Services.Messages.SmtpBuilder.BuildAsync(EmailAccount emailAccount) in C:\...\Libraries\Nop.Services\Messages\SmtpBuilder.cs:line 59
   --- End of inner exception stack trace ---
   at Nop.Services.Messages.SmtpBuilder.BuildAsync(EmailAccount emailAccount) in C:\...\Libraries\Nop.Services\Messages\SmtpBuilder.cs:line 78
   at Nop.Services.Messages.EmailSender.SendEmailAsync(EmailAccount emailAccount, String subject, String body, String fromAddress, String fromName, String toAddress, String toName, String replyTo, String replyToName, IEnumerable`1 bcc, IEnumerable`1 cc, String attachmentFilePath, String attachmentFileName, Int32 attachedDownloadId, IDictionary`2 headers) in C:\...\Libraries\Nop.Services\Messages\EmailSender.cs:line 202
   at Nop.Plugin.Misc.Sendinblue.Services.SendinblueEmailSender.SendEmailAsync(EmailAccount emailAccount, String subject, String body, String fromAddress, String fromName, String toAddress, String toName, String replyTo, String replyToName, IEnumerable`1 bcc, IEnumerable`1 cc, String attachmentFilePath, String attachmentFileName, Int32 attachedDownloadId, IDictionary`2 headers)
   at Nop.Services.Messages.QueuedMessagesSendTask.ExecuteAsync() in C:\...\Libraries\Nop.Services\Messages\QueuedMessagesSendTask.cs:line 57
IP address
0.152.29.81

**Comment by RomanovM** [comment]
>is there any problems on SendInBlue side ?

Yep, looks like a problem on their side. 
Is this error still happening?

**Comment by corentinchap** [comment]
Hello,

I reinstalled the plugin and it worked.
