### ISSUE TITLE
Exception thrown with Marketing Automation.

### ISSUE THREAD

**Issue by MattHobson1968** [nopSolutions/sendinblue-plugin-for-nopcommerce#5]
It appears that the Send in Blue Marketing Automation throws an exception if a person is browsing your Nopcommerce website and goes to the cart. This is for NopCommerce 4.2 and I am getting hundreds of these issues each day,

It appears that the cartItem.Customer.Email is not set

Short message	
SendinBlue Marketing Automation error: email is a required property for Identify and cannot be null.
Full message	
System.IO.InvalidDataException: email is a required property for Identify and cannot be null
   at SendinBlueMarketingAutomation.Model.Identify..ctor(String email, Object attributes)
   at Nop.Plugin.Misc.SendinBlue.Services.SendinBlueMarketingAutomationManager.HandleShoppingCartChangedEvent(ShoppingCartItem cartItem)

Any help on this would be appreciated.
Matt

**Comment by MattHobson1968** [comment]
Just some additional information for this case, this appears to happen for guest and registered users as in the error log it indicates either a registered users email address or guest.

**Comment by rafafontana** [comment]
Still happening this issue, any advance on this?

**Comment by rafafontana** [comment]
Still happening, any advance?

**Comment by mucahitaydinlik** [comment]
This problem is still continuing, i will uninstall the plugin. Can you solve it?

**Comment by RomanovM** [comment]
@mucahitaydinlik What version?

**Comment by mucahitaydinlik** [comment]
4.50.3

6 Ara 2023 Çar, saat 12:08 tarihinde Romanov Maksim <
***@***.***> şunu yazdı:

**Comment by aminaMuraina** [comment]
Hello any update or workaround?
